---
javascripts:
- base:
  - prototype
  - jquery
  - jquery-ui
  - shadowbox
  - effects
  - dragdrop
  - controls
  - application
  - jrails
  - cit
  - juggernaut_javascript
  - jquery.dimensions
  - jquery.tooltip
- portal:
  - prototype
  - tz
  - frontpage
stylesheets:
- base:
  - jquery-ui
  - cit
  - jquery.tooltip
- portal:
  - portal